# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9d3e57676016721916e5c46d7846fb17889285c9203b77e0efd1d93cf467e6b150a2dbf4426c3715b338cbf149bc308c14c3f8bc239d694625784b12121b375

test:
  secret_key_base: 4885441e6ffb0fc0020f813ec05e0a0dbef350ef8404ce606ca629afcd2663a3ddcfe5b78c245296ef027a6618cad25ec84c157e5a09ffa5490eb146b128deb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
